default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>
  schema_search_path: "public,shared_extensions"

development: &development
  <<: *default
  database: consul_development

test:
  <<: *default
  database: consul_test

production:
  <<: *development
  database: consul_production
  username: consul
  password: <%= ENV["CONSUL_DATABASE_PASSWORD"].presence %>
